### ISSUE TITLE
Launcher Log is blank.

### ISSUE THREAD

**Issue by ThunderGemios10** [download13/Mineshafter-Launcher#10]
Nothing is being shown in the launcher log, It's just blank.

**Comment by download13** [comment]
That shouldn't happen. Can you share a screenshot?

**Comment by ThunderGemios10** [comment]
Here you go:
![blank log](https://cloud.githubusercontent.com/assets/5190597/14947919/1611f26c-106d-11e6-8c53-bf5781f0ad30.png)

**Comment by download13** [comment]
Of the console log I mean. The launcher log tab isn't used by the mineshafter launcher.
Can you paste the output of running `java -jar Mineshafter-launcher.jar` from a command line?

**Comment by ThunderGemios10** [comment]
@download13 It looks fine, I can see the logs, But why the reason that the Launcher Log tab isn't used?

**Comment by download13** [comment]
It would require rewriting a lot of the functionality of the official launcher then injecting the rewrites. It could be done, but that's a lot more complexity and a lot more that could go wrong in the event that Mojang change the internals of the launcher.

Plus, if I introduced a bug that caused the launcher to crash, or be unable to load the interface then there would be no way to see the debugging information that might be needed to fix it.

Just sending debugging output to the console seemed a lot simpler and more fool-proof.

**Comment by ThunderGemios10** [comment]
@download13 Ah i see! But i wish The Launcher log could be used :)

**Comment by ThunderGemios10** [comment]
@download13 Also are you aware that Mineshafter.info is down?

**Comment by download13** [comment]
It doesn't seem to be now

**Comment by ThunderGemios10** [comment]
@download13 That's strange, It was down yesterday, I guess it's back up again. I was thinking you were doing maintenance xD

**Comment by ThunderGemios10** [comment]
@download13 Is skins working now? I was hoping for them to get fixed.

**Comment by download13** [comment]
Created an issue for it: #11
