### ISSUE TITLE
Using Mineshafter Skins with self-hosted server

### ISSUE THREAD

**Issue by Technohacker** [download13/Mineshafter-Launcher#16]
Hello :)
First of all, thanks for your efforts in making this launcher :D

I run a server on my own hardware on which me and some of my friends play.
Skins show up in singleplayer. However, on my server my skin turns out to be the default Alex skin.

Is there anything specific to do to make multiplayer skins to work?

I'm using SpigotMC (Minecraft 1.11.2)

Thanks!

**Comment by download13** [comment]
From what I can tell the server is responsible for getting skins and sending them to the client.

I could try bringing back the server proxy so offline mode servers will send skins, but realistically I'm not sure how long it'll take me to get around to that.

**Comment by Technohacker** [comment]
@download13 No pressure :)
I noticed many links to the Mineshafter server proxy to mineshafter.appspot.com but all lead to a 404.

I used a SkinsRestorer plugin but that only downloads skins from official Mojang servers.

**Comment by Technohacker** [comment]
Okay for the time being, this plugin solves my issue [CustomSkins by InventiveTalent](https://github.com/InventivetalentDev/CustomSkins). Closing for now :D
